name: "01 - Building Blocks"
on: 
  workflow_dispatch:
  push:
  # pull_request:

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps: 
      - name: Say Hello
        run: echo "Hello World!"
  echo-goodbye:
    runs-on: windows-latest
    steps:
      - name: Failed Step
        shell: bash
        run: |
          echo "I will fail!"
          exit 0
      - name: Say Goodbye
        run: echo "Goodbye!"

